/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiroalblanco;

import carreras.Fenix;
import carreras.Glz;
import carreras.Rugal;
import carreras.Sims;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leondev
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    private int i;
    
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);//Centrar formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Ptablero = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        m01 = new javax.swing.JLabel();
        m11 = new javax.swing.JLabel();
        m21 = new javax.swing.JLabel();
        m31 = new javax.swing.JLabel();
        m41 = new javax.swing.JLabel();
        m02 = new javax.swing.JLabel();
        m03 = new javax.swing.JLabel();
        m04 = new javax.swing.JLabel();
        m12 = new javax.swing.JLabel();
        m13 = new javax.swing.JLabel();
        m14 = new javax.swing.JLabel();
        m22 = new javax.swing.JLabel();
        m23 = new javax.swing.JLabel();
        m24 = new javax.swing.JLabel();
        m32 = new javax.swing.JLabel();
        m33 = new javax.swing.JLabel();
        m34 = new javax.swing.JLabel();
        m42 = new javax.swing.JLabel();
        m43 = new javax.swing.JLabel();
        m44 = new javax.swing.JLabel();
        m51 = new javax.swing.JLabel();
        m52 = new javax.swing.JLabel();
        m53 = new javax.swing.JLabel();
        m54 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        JL2 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        JL3 = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        JL4 = new javax.swing.JLabel();
        blanco2 = new javax.swing.JLabel();
        blanco1 = new javax.swing.JLabel();
        blanco3 = new javax.swing.JLabel();
        blanco4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PImagenes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        P1 = new javax.swing.JPanel();
        JL1 = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Glz");

        jLabel7.setText("Fenix");

        jLabel16.setText("Rugal");

        jLabel17.setText("Sins");

        m01.setText("-");

        m11.setText("-");

        m21.setText("-");

        m31.setText("-");

        m41.setText("-");

        m02.setText("-");

        m03.setText("-");

        m04.setText("-");

        m12.setText("-");

        m13.setText("-");

        m14.setText("-");

        m22.setText("-");

        m23.setText("-");

        m24.setText("-");

        m32.setText("-");

        m33.setText("-");

        m34.setText("-");
        m34.setToolTipText("");

        m42.setText("-");

        m43.setText("-");

        m44.setText("-");

        m51.setText("-");

        m52.setText("-");

        m53.setText("-");

        m54.setText("-");

        javax.swing.GroupLayout PtableroLayout = new javax.swing.GroupLayout(Ptablero);
        Ptablero.setLayout(PtableroLayout);
        PtableroLayout.setHorizontalGroup(
            PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PtableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PtableroLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(m01))
                    .addGroup(PtableroLayout.createSequentialGroup()
                        .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m04)
                            .addComponent(m03)
                            .addComponent(m02))))
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PtableroLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(m11)
                        .addGap(18, 18, 18)
                        .addComponent(m21)
                        .addGap(18, 18, 18)
                        .addComponent(m31)
                        .addGap(18, 18, 18)
                        .addComponent(m41)
                        .addGap(18, 18, 18)
                        .addComponent(m51))
                    .addGroup(PtableroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(m12)
                        .addGap(18, 18, 18)
                        .addComponent(m22)
                        .addGap(18, 18, 18)
                        .addComponent(m32)
                        .addGap(18, 18, 18)
                        .addComponent(m42)
                        .addGap(18, 18, 18)
                        .addComponent(m52))
                    .addGroup(PtableroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PtableroLayout.createSequentialGroup()
                                .addComponent(m14)
                                .addGap(18, 18, 18)
                                .addComponent(m24)
                                .addGap(18, 18, 18)
                                .addComponent(m34)
                                .addGap(18, 18, 18)
                                .addComponent(m44)
                                .addGap(18, 18, 18)
                                .addComponent(m54))
                            .addGroup(PtableroLayout.createSequentialGroup()
                                .addComponent(m13)
                                .addGap(18, 18, 18)
                                .addComponent(m23)
                                .addGap(18, 18, 18)
                                .addComponent(m33)
                                .addGap(18, 18, 18)
                                .addComponent(m43)
                                .addGap(18, 18, 18)
                                .addComponent(m53)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PtableroLayout.setVerticalGroup(
            PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PtableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m01)
                    .addComponent(m11)
                    .addComponent(m21)
                    .addComponent(m31)
                    .addComponent(m41)
                    .addComponent(m51)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m02)
                    .addComponent(m12)
                    .addComponent(m22)
                    .addComponent(m32)
                    .addComponent(m42)
                    .addComponent(m52)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m03)
                    .addComponent(jLabel17)
                    .addComponent(m13)
                    .addComponent(m23)
                    .addComponent(m33)
                    .addComponent(m43)
                    .addComponent(m53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PtableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m04)
                        .addComponent(m14)
                        .addComponent(m24)
                        .addComponent(m34)
                        .addComponent(m44)
                        .addComponent(m54)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(Ptablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 210, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Corsiva Hebrew", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIRO AL BLANCO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Programa concurente - thread");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, -1));

        P2.setBackground(new java.awt.Color(161, 55, 42));

        JL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha2.png"))); // NOI18N

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL2)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 390, 90));

        P3.setBackground(new java.awt.Color(161, 55, 42));

        JL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha3.png"))); // NOI18N

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL3)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 390, 90));

        P4.setBackground(new java.awt.Color(161, 55, 42));

        JL4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha4.png"))); // NOI18N

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 390, 90));

        blanco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(blanco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 100, 90));

        blanco1.setBackground(new java.awt.Color(204, 204, 204));
        blanco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(blanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 100, 90));

        blanco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(blanco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 100, 90));

        blanco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(blanco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 100, 90));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setText("Iniciar");
        btnIniciar.setToolTipText("");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madera.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 200, 50));

        PImagenes.setBorder(new javax.swing.border.MatteBorder(null));
        PImagenes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fenix-mug.JPG"))); // NOI18N
        jLabel9.setText("jLabel9");
        PImagenes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rugal.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        PImagenes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sims.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        PImagenes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 90));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Speedy_Gonzales.svg.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        PImagenes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madera.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        PImagenes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 430));

        getContentPane().add(PImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 430));

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 210, 300));

        P1.setBackground(new java.awt.Color(161, 55, 42));

        JL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha1.png"))); // NOI18N

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL1)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        getContentPane().add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 10, 430));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 80, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, -1));

        jLabel3.setBackground(new java.awt.Color(161, 55, 42));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madera.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        btnIniciar.setEnabled(false);
        jButton1.setEnabled(false);
        carrera.registrarFlechas();
        carrera.iniciar();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        carrera.reiniciar();
        JL1.setLocation(carrera.flechas[0].getCoorX(),carrera.flechas[0].getCoorY());
        JL2.setLocation(carrera.flechas[1].getCoorX(),carrera.flechas[1].getCoorY());
        JL3.setLocation(carrera.flechas[2].getCoorX(),carrera.flechas[2].getCoorY());
        JL4.setLocation(carrera.flechas[3].getCoorX(),carrera.flechas[3].getCoorY());
        
        
        btnIniciar.setEnabled(true);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JL1;
    public static javax.swing.JLabel JL2;
    public static javax.swing.JLabel JL3;
    public static javax.swing.JLabel JL4;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    public static javax.swing.JPanel P4;
    private javax.swing.JPanel PImagenes;
    private javax.swing.JPanel Ptablero;
    public static javax.swing.JLabel blanco1;
    public static javax.swing.JLabel blanco2;
    public static javax.swing.JLabel blanco3;
    public static javax.swing.JLabel blanco4;
    public static javax.swing.JButton btnIniciar;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JLabel lblLinea;
    public static javax.swing.JLabel m01;
    public static javax.swing.JLabel m02;
    public static javax.swing.JLabel m03;
    public static javax.swing.JLabel m04;
    public static javax.swing.JLabel m11;
    public static javax.swing.JLabel m12;
    public static javax.swing.JLabel m13;
    public static javax.swing.JLabel m14;
    public static javax.swing.JLabel m21;
    public static javax.swing.JLabel m22;
    public static javax.swing.JLabel m23;
    public static javax.swing.JLabel m24;
    public static javax.swing.JLabel m31;
    public static javax.swing.JLabel m32;
    public static javax.swing.JLabel m33;
    public static javax.swing.JLabel m34;
    public static javax.swing.JLabel m41;
    public static javax.swing.JLabel m42;
    public static javax.swing.JLabel m43;
    public static javax.swing.JLabel m44;
    public static javax.swing.JLabel m51;
    public static javax.swing.JLabel m52;
    public static javax.swing.JLabel m53;
    public static javax.swing.JLabel m54;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables

    
}
